# Author: Wil Coiner
# Date: 03/13/20
# Description: Test file for testing Xiangqi class functionality

### Instantiation game for testing ###
def main():
    game = XiangqiGame()
    game._gameboard.print_board()
    game.make_move('c1', 'e3')  # r
    print("1")
    game._gameboard.print_board()
    game.make_move('e7', 'e6')  # b
    print("2")
    game._gameboard.print_board()
    game.make_move('b1', 'd2')  # r
    print("3")
    game._gameboard.print_board()
    game.make_move('h10', 'g8')  # b
    print("4")
    game._gameboard.print_board()
    game.make_move('h1', 'i3')  # r
    print("5")
    game._gameboard.print_board()
    game.make_move('g10', 'e8')
    print("6")
    game._gameboard.print_board()
    game.make_move('h3', 'g3')
    print("7")
    game._gameboard.print_board()
    game.make_move('i7', 'i6')
    print("8")
    game._gameboard.print_board()
    game.make_move('i1', 'h1')
    print("9")
    game._gameboard.print_board()
    game.make_move('g7', 'g6')
    print("10")
    game._gameboard.print_board()
    game.make_move('d2', 'f3')
    print("11")
    game._gameboard.print_board()
    game.make_move('h8', 'i8')
    print("12")
    game._gameboard.print_board()
    game.make_move('d1', 'e2')
    print("13")
    game._gameboard.print_board()
    game.make_move('b8', 'd8')
    print("14")
    game._gameboard.print_board()
    game.make_move('a1', 'd1')
    print("15")
    game._gameboard.print_board()
    game.make_move('b10', 'c8')
    print("16")
    game._gameboard.print_board()
    game.make_move('g4', 'g5')
    print("17")
    game._gameboard.print_board()
    game.make_move('d10', 'e9')
    print("18")
    game._gameboard.print_board()
    game.make_move('g5', 'g6')
    print("19")
    game._gameboard.print_board()
    game.make_move('g8', 'f6')
    print("20")
    game._gameboard.print_board()
    game.make_move('g3', 'h3')
    print("21")
    game._gameboard.print_board()
    game.make_move('f6', 'e4')
    print("22")
    game._gameboard.print_board()
    game.make_move('d1', 'd4')
    print("23")
    game._gameboard.print_board()
    game.make_move('a10', 'b10')
    print("24")
    game._gameboard.print_board()
    game.make_move('d4', 'e4')
    print("25")
    game._gameboard.print_board()
    game.make_move('i8', 'i4')
    print("26")
    game._gameboard.print_board()
    game.make_move('e1', 'd1')
    print("27")
    game._gameboard.print_board()
    game.make_move('b10', 'b3')
    print("28")
    game._gameboard.print_board()
    game.make_move('f3', 'e5')
    print("29")
    game._gameboard.print_board()
    game.make_move('i10', 'i7')
    print("30")
    game._gameboard.print_board()
    game.make_move('h1', 'h10')
    print("31")
    game._gameboard.print_board()
    game.make_move('e6', 'e5')
    print("32")
    game._gameboard.print_board()
    game.make_move('h10', 'f10')
    print("33")
    game._gameboard.print_board()
    game.make_move('e10', 'f10')
    print("34")
    game._gameboard.print_board()
    game.make_move('e4', 'i4')
    print("35")
    game._gameboard.print_board()
    game.make_move('i7', 'd7')
    print("36")
    game._gameboard.print_board()
    game.make_move('c4', 'c5')
    print("37")
    game._gameboard.print_board()
    game.make_move('d1', 'e1')
    print('38')
    game._gameboard.print_board()
    game.make_move('b3', 'b1')
    print("39")
    game._gameboard.print_board()
    game.make_move('e2', 'd1')
    print("40")
    game._gameboard.print_board()
    game.make_move('b1', 'd1')
    print("41")
    game._gameboard.print_board()
    game.make_move('e1', 'e2')
    print("42")
    game._gameboard.print_board()
    game.make_move('d7', 'd2')
    print("43")
    game._gameboard.print_board()
    print(game.get_game_state())
